<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Atletas' => $baseDir . '/model/Atletas.class.php',
    'Carrinho' => $baseDir . '/model/Carrinho.class.php',
    'Categorias' => $baseDir . '/model/Categorias.class.php',
    'Clientes' => $baseDir . '/model/Clientes.class.php',
    'Conexao' => $baseDir . '/model/Conexao.class.php',
    'Config' => $baseDir . '/model/Config.class.php',
    'Confirm' => $baseDir . '/model/Confirm.class.php',
    'Correios' => $baseDir . '/model/Correios.class.php',
    'Cupom' => $baseDir . '/model/Cupom.class.php',
    'Entregue' => $baseDir . '/model/Entregue.class.php',
    'EnviarEmail' => $baseDir . '/model/EnviarEmail.class.php',
    'ImageUpload' => $baseDir . '/model/ImageUpload.class.php',
    'Itens' => $baseDir . '/model/Itens.class.php',
    'Login' => $baseDir . '/model/Login.class.php',
    'MP' => $vendorDir . '/mercadopago/sdk/lib/mercadopago.php',
    'MPRestClient' => $vendorDir . '/mercadopago/sdk/lib/mercadopago.php',
    'MercadoPagoException' => $vendorDir . '/mercadopago/sdk/lib/mercadopago.php',
    'PHPMailer' => $baseDir . '/model/class.phpmailer.php',
    'POP3' => $baseDir . '/model/class.pop3.php',
    'PagamentoMP' => $baseDir . '/model/PagamentoMP.class.php',
    'PagamentoPS' => $baseDir . '/model/PagamentoPS.class.php',
    'Paginacao' => $baseDir . '/model/Paginacao.class.php',
    'Pedidos' => $baseDir . '/model/Pedidos.class.php',
    'Produtos' => $baseDir . '/model/Produtos.class.php',
    'ProdutosImages' => $baseDir . '/model/ProdutosImages.class.php',
    'Rotas' => $baseDir . '/model/Rotas.class.php',
    'SMTP' => $baseDir . '/model/class.smtp.php',
    'Sistema' => $baseDir . '/model/Sistema.class.php',
    'Template' => $baseDir . '/model/Template.class.php',
    'User' => $baseDir . '/model/User.class.php',
);
