<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5d9e521db9f8700292f0c8e251233174
{
    public static $files = array (
        'f084d01b0a599f67676cffef638aa95b' => __DIR__ . '/..' . '/smarty/smarty/libs/bootstrap.php',
    );

    public static $classMap = array (
        'Atletas' => __DIR__ . '/../..' . '/model/Atletas.class.php',
        'Carrinho' => __DIR__ . '/../..' . '/model/Carrinho.class.php',
        'Categorias' => __DIR__ . '/../..' . '/model/Categorias.class.php',
        'Clientes' => __DIR__ . '/../..' . '/model/Clientes.class.php',
        'Conexao' => __DIR__ . '/../..' . '/model/Conexao.class.php',
        'Config' => __DIR__ . '/../..' . '/model/Config.class.php',
        'Confirm' => __DIR__ . '/../..' . '/model/Confirm.class.php',
        'Correios' => __DIR__ . '/../..' . '/model/Correios.class.php',
        'Cupom' => __DIR__ . '/../..' . '/model/Cupom.class.php',
        'Entregue' => __DIR__ . '/../..' . '/model/Entregue.class.php',
        'EnviarEmail' => __DIR__ . '/../..' . '/model/EnviarEmail.class.php',
        'ImageUpload' => __DIR__ . '/../..' . '/model/ImageUpload.class.php',
        'Itens' => __DIR__ . '/../..' . '/model/Itens.class.php',
        'Login' => __DIR__ . '/../..' . '/model/Login.class.php',
        'MP' => __DIR__ . '/..' . '/mercadopago/sdk/lib/mercadopago.php',
        'MPRestClient' => __DIR__ . '/..' . '/mercadopago/sdk/lib/mercadopago.php',
        'MercadoPagoException' => __DIR__ . '/..' . '/mercadopago/sdk/lib/mercadopago.php',
        'PHPMailer' => __DIR__ . '/../..' . '/model/class.phpmailer.php',
        'POP3' => __DIR__ . '/../..' . '/model/class.pop3.php',
        'PagamentoMP' => __DIR__ . '/../..' . '/model/PagamentoMP.class.php',
        'PagamentoPS' => __DIR__ . '/../..' . '/model/PagamentoPS.class.php',
        'Paginacao' => __DIR__ . '/../..' . '/model/Paginacao.class.php',
        'Pedidos' => __DIR__ . '/../..' . '/model/Pedidos.class.php',
        'Produtos' => __DIR__ . '/../..' . '/model/Produtos.class.php',
        'ProdutosImages' => __DIR__ . '/../..' . '/model/ProdutosImages.class.php',
        'Rotas' => __DIR__ . '/../..' . '/model/Rotas.class.php',
        'SMTP' => __DIR__ . '/../..' . '/model/class.smtp.php',
        'Sistema' => __DIR__ . '/../..' . '/model/Sistema.class.php',
        'Template' => __DIR__ . '/../..' . '/model/Template.class.php',
        'User' => __DIR__ . '/../..' . '/model/User.class.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit5d9e521db9f8700292f0c8e251233174::$classMap;

        }, null, ClassLoader::class);
    }
}
