<div id="content">
    <h1 style="text-align: center; color: #333333;"><img src="/images/items_shop/items/craftmachine.gif">CRAFTING SYSTEM<img src="/images/items_shop/items/craftmachine.gif"></h1><br>
    <p style="text-align: center; color: #5a2800; font-family: Verdana, Tahoma, Helvetica, sans-serif; font-size: 16px; font-weight: bold; margin-bottom: 10px;"><img src="https://static.retrocores.com/images/items_v2/2173.gif"> Jewelry <img src="https://static.retrocores.com/images/items_v2/2173.gif"></p>
    <p style="color: #5a2800; font-family: Verdana, Tahoma, Helvetica, sans-serif; font-size: 12px; text-align: center;">&nbsp;</p>
<table style="font-size: 13px; color: #5a2800; margin: 10px auto 0px; border-spacing: 1px; font-family: Verdana, Tahoma, Helvetica, sans-serif; width: 400px; box-shadow: #000000 1px 1px 10px;" cellspacing="1" cellpadding="10">
        <tbody>
            <tr style="background-color: #4a4a45;">
                <td style="cursor: pointer; width: 390.344px; height: 18px; text-align: center;"><strong><span style="color: #ffffff;">Jewelry</span></strong></td>
                <td style="cursor: pointer; width: 385.484px; height: 18px; text-align: center;"><strong><span style="color: #ffffff;">Item required</span></strong></td>
            </tr>
<tr style="height: 18px;" bgcolor="#F1E0C6"><td><img src="/images/items_shop/items/item_gifs/2213.gif">Dwarven Ring (4x)</td><td><img src="/images/items_shop/items/item_gifs/5937.gif">1x Mystic Ore<br><img src="/images/items_shop/items/item_gifs/8147.gif">2x Blue Crystal<br><img src="/images/items_shop/items/item_gifs/8145.gif">2x Red Crystal<br><img src="/images/items_shop/items/item_gifs/8149.gif">2x Blue Crystal</td></tr>
<tr style="height: 18px;" bgcolor="#D4C0A1"><td><img src="/images/items_shop/items/item_gifs/2168.gif">Life Ring (4x)</td><td><img src="/images/items_shop/items/item_gifs/5937.gif">5x Mystic Ore<br><img src="/images/items_shop/items/item_gifs/8149.gif">20x Green Crystal</td></tr>
<tr style="height: 18px;" bgcolor="#F1E0C6"><td><img src="/images/items_shop/items/item_gifs/2208.gif">Axe Ring (4x)</td><td><img src="/images/items_shop/items/item_gifs/5937.gif">3x Mystic Ore<br><img src="/images/items_shop/items/item_gifs/8144.gif">10x White Crystal</td></tr>
<tr style="height: 18px;" bgcolor="#D4C0A1"><td><img src="/images/items_shop/items/item_gifs/2207.gif">Sword Ring (4x)</td><td><img src="/images/items_shop/items/item_gifs/5937.gif">3x Mystic Ore<br><img src="/images/items_shop/items/item_gifs/8147.gif">20x Green Crystal<br><img src="/images/items_shop/items/item_gifs/8148.gif">20x Yellow Crystal</td></tr>
<tr style="height: 18px;" bgcolor="#F1E0C6"><td><img src="/images/items_shop/items/item_gifs/2209.gif">Club Ring (4x)</td><td><img src="/images/items_shop/items/item_gifs/5937.gif">1x Mystic Ore<br><img src="/images/items_shop/items/item_gifs/8144.gif">20x White Crystal<br><img src="/images/items_shop/items/item_gifs/8147.gif">20x Red Crystal</td></tr>
<tr style="height: 18px;" bgcolor="#D4C0A1"><td><img src="/images/items_shop/items/item_gifs/2214.gif">Ring of Healing (4x)</td><td><img src="/images/items_shop/items/item_gifs/5937.gif">12x Mystic Ore<br><img src="/images/items_shop/items/item_gifs/8147.gif">40x Red Crystal</td></tr>
<tr style="height: 18px;" bgcolor="#F1E0C6"><td><img src="/images/items_shop/items/item_gifs/2167.gif">Energy Ring (4x)</td><td><img src="/images/items_shop/items/item_gifs/5937.gif">20x Mystic Ore<br><img src="/images/items_shop/items/item_gifs/8145.gif">20x Blue Crystal</td></tr>
<tr style="height: 18px;" bgcolor="#D4C0A1"><td><img src="/images/items_shop/items/item_gifs/2169.gif">Time Ring (4x)</td><td><img src="/images/items_shop/items/item_gifs/5937.gif">8x Mystic Ore<br><img src="/images/items_shop/items/item_gifs/8145.gif">10x Blue Crystal<br><img src="/images/items_shop/items/item_gifs/8147.gif">10x Red Crystal<br><img src="/images/items_shop/items/item_gifs/8148.gif">10x Yellow Crystal</td></tr>
<tr style="height: 18px;" bgcolor="#F1E0C6"><td><img src="/images/items_shop/items/item_gifs/2170.gif">Silver Amulet (200x)</td><td><img src="/images/items_shop/items/item_gifs/5937.gif">2x Mystic Ore<br><img src="/images/items_shop/items/item_gifs/2145.gif">5x Small Diamond</td></tr>
<tr style="height: 18px;" bgcolor="#D4C0A1"><td><img src="/images/items_shop/items/item_gifs/2172.gif">Bronze Amulet (200x)</td><td><img src="/images/items_shop/items/item_gifs/5937.gif">2x Mystic Ore<br><img src="/images/items_shop/items/item_gifs/2145.gif">5x Small Diamond</td></tr>
<tr style="height: 18px;" bgcolor="#F1E0C6"><td><img src="/images/items_shop/items/item_gifs/2199.gif">Garlic Necklace (150x)</td><td><img src="/images/items_shop/items/item_gifs/5937.gif">2x Mystic Ore<br><img src="/images/items_shop/items/item_gifs/2145.gif">5x Small Diamond</td></tr>
<tr style="height: 18px;" bgcolor="#D4C0A1"><td><img src="/images/items_shop/items/item_gifs/2200.gif">Protection Amulet (250x)</td><td><img src="/images/items_shop/items/item_gifs/5937.gif">2x Mystic Ore<br><img src="/images/items_shop/items/item_gifs/8144.gif">10x White Crystal<br><img src="/images/items_shop/items/item_gifs/2145.gif">2x Small Diamond</td></tr>
<tr style="height: 18px;" bgcolor="#F1E0C6"><td><img src="/images/items_shop/items/item_gifs/2201.gif">Dragon Necklace (200x)</td><td><img src="/images/items_shop/items/item_gifs/5937.gif">2x Mystic Ore<br><img src="/images/items_shop/items/item_gifs/8149.gif">20x Green Crystal<br><img src="/images/items_shop/items/item_gifs/2149.gif">2x Small Emerald</td></tr>
<tr style="height: 18px;" bgcolor="#D4C0A1"><td><img src="/images/items_shop/items/item_gifs/2198.gif">Elven Amulet (50x)</td><td><img src="/images/items_shop/items/item_gifs/5937.gif">3x Mystic Ore<br><img src="/images/items_shop/items/item_gifs/2146.gif">4x Small Sapphire<br><img src="/images/items_shop/items/item_gifs/2149.gif">4x Small Emerald<br><img src="/images/items_shop/items/item_gifs/2145.gif">4x Small Diamond</td></tr>
        </tbody>
    </table>
    <p>&nbsp;</p>
    <div style="clear:both;"></div><br>
    <img src="templates/tibiana/images/line_body.gif" align="center" height="7" width="100%">
</div>
