<div id="content">

					<p><img style="vertical-align: middle; color: #5a2800; font-family: Verdana, Tahoma, Helvetica, sans-serif; font-size: 12px; background-color: #102129; display: block; margin-left: auto; margin-right: auto;" src="https://classicot.com/layout/images/line_body.gif" width="100%" height="7" align="center"><img style="display: block; margin-left: 330px; margin-right: auto;" src="/images/outfit.png" align="left"><img style="vertical-align: middle; color: #5a2800; font-family: Verdana, Tahoma, Helvetica, sans-serif; font-size: 12px; background-color: #102129; display: block; margin-left: auto; margin-right: auto;" src="https://classicot.com/layout/images/line_body.gif" width="100%" height="7" align="center"></p>
<table style="font-size: 13px; color: #5a2800; margin: 10px auto 0px; width: 441px; border-spacing: 1px; font-family: Verdana, Tahoma, Helvetica, sans-serif; background-color: #102129; box-shadow: #000000 1px 1px 10px;" cellspacing="1" cellpadding="10">
<tbody>
<tr>
					<p>&nbsp;</p>
<table style="font-size: 13px; color: #5a2800; margin: 10px 20px 0px; border-spacing: 1px; font-family: Verdana, Tahoma, Helvetica, sans-serif; width: 859px; background-color: #102129; float: left; box-shadow: #000000 1px 1px 10px; height: 335px;" cellspacing="1" cellpadding="10">
<tbody>

<h4 style="text-align: center;"><span style="color: #333333;">These are the new outfits from Karma. To acquire them, you can access our in-game store under the Outfits tab.</span></h4>


<tr style="height: 50px;" bgcolor="#D4C0A1">
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background: #f1e0c6; width: 177px; height: 50px; text-align: center;">&nbsp;<a href=""><img src="/outfits/animoutfit.php?id=655&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=656&addons=0&head=59&body=0&legs=114&feet=114"></a><br><a style="box-sizing: border-box; color: #0042a0; font-weight: bold; background-color: transparent; text-decoration-line: none !important;" href="">New Hunter Outfit</a></td>
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background: #f1e0c6; width: 177px; height: 50px; text-align: center;">&nbsp;<a href=""><img src="/outfits/animoutfit.php?id=657&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=658&addons=0&head=59&body=0&legs=114&feet=114"></a><br><a style="box-sizing: border-box; color: #0042a0; font-weight: bold; background-color: transparent; text-decoration-line: none !important;" href="">New Hunter Outfit</a></td>
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background: #f1e0c6; width: 160px; height: 50px; text-align: center;"><a href=""><img src="/outfits/animoutfit.php?id=659&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=660&addons=0&head=59&body=0&legs=114&feet=114"></a><br><strong><a style="background-color: transparent; text-align: center; box-sizing: border-box; color: #0042a0; font-weight: bold; text-decoration-line: none !important;" href="">New Mage Outfit</a></strong></td>
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background: #f1e0c6; width: 177px; height: 50px; text-align: center;"><a href=""><img src="/outfits/animoutfit.php?id=661&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=662&addons=0&head=59&body=0&legs=114&feet=114"></a><br><a style="background-color: transparent; text-align: center; box-sizing: border-box; color: #0042a0; font-weight: bold; text-decoration-line: none !important;" href="">New Knight Outfit</a></td>
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background: #f1e0c6; width: 188px; height: 50px; text-align: center;"><a href=""><img src="/outfits/animoutfit.php?id=663&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=664&addons=0&head=59&body=0&legs=114&feet=114"></a><br><a style="background-color: transparent; text-align: center; box-sizing: border-box; color: #0042a0; font-weight: bold; text-decoration-line: none !important;" href="">New Nobleman Outfit</a></td>
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background: #f1e0c6; width: 188px; height: 50px; text-align: center;"><a href=""><img src="/outfits/animoutfit.php?id=224&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=231&addons=0&head=59&body=0&legs=114&feet=114"></a><br><a style="background-color: transparent; text-align: center; box-sizing: border-box; color: #0042a0; font-weight: bold; text-decoration-line: none !important;" href="">New Married Outfit</a></td>
</tr>
<tr style="height: 32px;" bgcolor="#F1E0C6">
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background: #d4c0a1; font-weight: bold; width: 156px; height: 32px; text-align: center;">&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://exordion.com.br/?Shields"><img src="/outfits/animoutfit.php?id=665&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=666&addons=0&head=59&body=0&legs=114&feet=114"></a>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<a style="box-sizing: border-box; color: #0042a0; font-weight: bold; background-color: transparent; text-decoration-line: none !important;" href="">New Summoner Outfit</a>&nbsp;</td>
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background: #d4c0a1; width: 177px; height: 32px; text-align: center;">&nbsp;&nbsp;<a href=""><img src="/outfits/animoutfit.php?id=669&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=670&addons=0&head=59&body=0&legs=114&feet=114"></a><br><a style="box-sizing: border-box; color: #0042a0; font-weight: bold; background-color: transparent; text-decoration-line: none !important;" href="">New Barbarian Outfit</a></td>
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background: #d4c0a1; width: 160px; height: 32px; text-align: center;"><a href=""><img src="/outfits/animoutfit.php?id=671&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=672&addons=0&head=59&body=0&legs=114&feet=114"></a><br><a style="background-color: transparent; text-align: center; box-sizing: border-box; color: #0042a0; font-weight: bold; text-decoration-line: none !important;" href=""><strong>New Wizard Outfit</strong></a></td>
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background: #d4c0a1; width: 177px; height: 32px; text-align: center;"><a href=""><img src="/outfits/animoutfit.php?id=673&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=674&addons=0&head=59&body=0&legs=114&feet=114"></a><br><a style="background-color: transparent; text-align: center; box-sizing: border-box; color: #0042a0; font-weight: bold; text-decoration-line: none !important;" href="">New Druid Outfit</a></td>
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background: #d4c0a1; width: 188px; height: 32px; text-align: center;"><a href=""><img src="/outfits/animoutfit.php?id=675&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=676&addons=0&head=59&body=0&legs=114&feet=114"></a><br><a style="background-color: transparent; text-align: center; box-sizing: border-box; color: #0042a0; font-weight: bold; text-decoration-line: none !important;" href="">New Oriental Outfit</a></td>
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background: #d4c0a1; width: 188px; height: 32px; text-align: center;"><a href=""><img src="/outfits/animoutfit.php?id=126&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=127&addons=0&head=59&body=0&legs=114&feet=114"></a><br><a style="background-color: transparent; text-align: center; box-sizing: border-box; color: #0042a0; font-weight: bold; text-decoration-line: none !important;" href="">Special Citizen Outfit</a></td>
</tr>
<tr style="height: 32px;" bgcolor="#F1E0C6">
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-weight: bold; width: 156px; height: 32px; text-align: center;">&nbsp;<img src="/outfits/animoutfit.php?id=677&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=678&addons=0&head=59&body=0&legs=114&feet=114"></a><br><a style="background-color: transparent; text-align: center; box-sizing: border-box; color: #0042a0; font-weight: bold; text-decoration-line: none !important;" href="">New Pirate Outfit</a></td>
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; width: 177px; height: 32px; text-align: center;">&nbsp;&nbsp;<a href=""><img src="/outfits/animoutfit.php?id=679&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=680&addons=0&head=59&body=0&legs=114&feet=114"></a><br>&nbsp;<a style="box-sizing: border-box; color: #0042a0; font-weight: bold; background-color: transparent; text-decoration-line: none !important;" href="">New Assassin Outfit</a></td>
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; width: 160px; height: 32px; text-align: center;"><img src="/outfits/animoutfit.php?id=681&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=682&addons=0&head=59&body=0&legs=114&feet=114"></a><br><a style="background-color: transparent; text-align: center; box-sizing: border-box; color: #0042a0; font-weight: bold; text-decoration-line: none !important;" href="">New Beggar Outfit</a></td>
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; width: 177px; height: 32px; text-align: center;"><img src="/outfits/animoutfit.php?id=683&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=684&addons=0&head=59&body=0&legs=114&feet=114"></a><br><a style="background-color: transparent; text-align: center; box-sizing: border-box; color: #0042a0; font-weight: bold; text-decoration-line: none !important;" href="">New Shaman Outfit</a></td>
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; width: 188px; height: 32px; text-align: center;"><img src="/outfits/animoutfit.php?id=685&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=686&addons=0&head=59&body=0&legs=114&feet=114"></a><br><a style="background-color: transparent; text-align: center; box-sizing: border-box; color: #0042a0; font-weight: bold; text-decoration-line: none !important;" href="">Golden Outfit</a></td>
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; width: 188px; height: 32px; text-align: center;"><img src="/outfits/animoutfit.php?id=132&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=141&addons=0&head=59&body=0&legs=114&feet=114"></a><br><a style="background-color: transparent; text-align: center; box-sizing: border-box; color: #0042a0; font-weight: bold; text-decoration-line: none !important;" href="">Advanced Noble Outfit</a></td>
</tr>
<tr style="height: 18px; background-color: #d4c0a1;" bgcolor="#D4C0A1">
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-weight: bold; width: 156px; height: 18px; text-align: center;"><a href=""><img src="/outfits/animoutfit.php?id=704&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=705&addons=0&head=59&body=0&legs=114&feet=114"></a><br><a style="background-color: transparent; text-align: center; box-sizing: border-box; color: #0042a0; font-weight: bold; text-decoration-line: none !important;" href="">Dragon Slayer Outfit</a></td>
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; width: 177px; height: 18px; text-align: center;">
<img style="font-weight: bold; text-align: center; display: block; margin-left: auto; margin-right: auto;" src="/outfits/animoutfit.php?id=128&addons=0&head=59&body=0&legs=114&feet=114" width="32" height="32"><img style="font-weight: bold; text-align: center; display: block; margin-left: auto; margin-right: auto;" src="/outfits/animoutfit.php?id=171&addons=0&head=59&body=0&legs=114&feet=114" width="32" height="32"><a style="background-color: transparent; text-align: center; box-sizing: border-box; color: #0042a0; font-weight: bold; text-decoration-line: none !important;" href="">Advanced Citizen Outfit</a></p>
</td>
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; width: 160px; height: 18px; text-align: center;"><img src="/outfits/animoutfit.php?id=130&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=169&addons=0&head=59&body=0&legs=114&feet=114"></a><br><strong><a style="background-color: transparent; text-align: center; box-sizing: border-box; color: #0042a0; font-weight: bold; text-decoration-line: none !important;" href="">Advanced Mage Outfit</a></strong></td>
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; width: 177px; height: 18px; text-align: center;"><img src="/outfits/animoutfit.php?id=129&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=167&addons=0&head=59&body=0&legs=114&feet=114"></a><br><a style="background-color: transparent; text-align: center; box-sizing: border-box; color: #0042a0; font-weight: bold; text-decoration-line: none !important;" href="">Advanced Hunter Outfit</a></td>
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; width: 188px; height: 18px; text-align: center;"><img src="/outfits/animoutfit.php?id=131&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=170&addons=0&head=59&body=0&legs=114&feet=114"></a><br><a style="background-color: transparent; text-align: center; box-sizing: border-box; color: #0042a0; font-weight: bold; text-decoration-line: none !important;" href="">Advanced Knight Outfit</a></td>
<td style="cursor: url('http://35.198.43.175/images/cursor/cursor.png'), url('http://35.198.43.175/images/cursor/cursor-click.png'), pointer; padding: 4px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; width: 188px; height: 18px; text-align: center;"><img src="/outfits/animoutfit.php?id=142&addons=0&head=59&body=0&legs=114&feet=114"><img src="/outfits/animoutfit.php?id=134&addons=0&head=59&body=0&legs=114&feet=114"></a><br><a style="background-color: transparent; text-align: center; box-sizing: border-box; color: #0042a0; font-weight: bold; text-decoration-line: none !important;" href="">Advanced Warrior Outfit</a></td>
</tr>
</tbody>
</table>
<p>&nbsp; &nbsp;&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>					<div style="clear:both;"></div>
					<br>
						
							<img src="templates/tibiana/images/line_body.gif" align="center" height="7" width="100%">
							<img src="templates/tibiana/images/blank.gif">
						

					<div align="center" style="font-face:verdana; font-size:10px">
					</div>
				</div>